version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-7.5.2}
    user: root
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
      - source: elastic_logs_config
        target: /usr/share/elasticsearch/config/log4j2.properties
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - TAKE_FILE_OWNERSHIP=true 
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-changeme}
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      - discovery.type=single-node
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs:rw
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION:-7.5.2}
    user: root
    ports:
      - "5000:5000"
      - "9600:9600"
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_logs_config
        target: /usr/share/logstash/config/log4j2.properties
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/logs:/usr/share/logstash/logs
    environment:
      - ELASTIC_USER=${ELASTIC_USER:-elastic}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-changeme}
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    depends_on:
      - elasticsearch  
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION:-7.5.2}
    environment:
      - ELASTIC_USER=${ELASTIC_USER:-elastic}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-changeme}
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch  
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
  
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:${ELASTIC_VERSION:-7.5.2}
    user: root
    environment:
      - setup.kibana.host=${KIBANA_HOST}:5601
      - output.elasticsearch.hosts=["${ELASTIC_HOST}:9200"]
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD-changeme}
    configs:
      - source: metricbeat_config
        target: /usr/share/metricbeat/metricbeat.yml
    command: -system.hostfs=/hostfs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
      - ./metricbeat/dashboards:/usr/share/metricbeat/kibana/7/dashboard:ro
    depends_on:
      - elasticsearch
      - kibana  
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELASTIC_VERSION:-7.5.2}
    # https://github.com/docker/swarmkit/issues/1951
    # Need to override user so we can access the log files, and docker.sock
    user: root
    configs:
      - source: filebeat_config
        target: /usr/share/filebeat/filebeat.yml
    volumes:
      - filebeat_data:/usr/share/filebeat/data
      - /var/run/docker.sock:/var/run/docker.sock
      # This is needed for filebeat to load container log path as specified in filebeat.yml
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      # # This is needed for filebeat to load jenkins build log path as specified in filebeat.yml
      # - /var/lib/docker/volumes/jenkins_home/_data/jobs/:/var/lib/docker/volumes/jenkins_home/_data/jobs/:ros
      # This is needed for filebeat to load logs for system and auth modules
      - /var/log/:/var/log/
      # This is needed for filebeat to load logs for auditd module
      # - /var/log/audit/:/var/log/audit/:ro
      # This is needed for filebeat to load elasticsearch logs
      - ./elasticsearch/logs:/var/log/elasticsearch
      - ./logstash/logs:/var/log/logstash
      - ./filebeat/dashboards:/usr/share/filebeat/kibana/7/dashboard:ro
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-elasticsearch:9200}
      - KIBANA_HOST=${KIBANA_HOST:-kibana:5601}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
    # disable strict permission checks
    command: "--strict.perms=false"
    depends_on:
      - elasticsearch
      - kibana  
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
  
  ##################### AUDITBEAT INSIDE A CONTAINER IS UDER DEVELOPEMENT ####################
  # auditbeat:
  #   image: docker.elastic.co/beats/auditbeat:${ELASTIC_VERSION:-7.5.2}
  #   # https://github.com/docker/swarmkit/issues/1951
  #   # Need to override user so we can access the log files, and docker.sock
  #   user: root
  #   configs:
  #     - source: auditbeat_config
  #       target: /usr/share/auditbeat/auditbeat.yml
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     # This is needed for filebeat to load container log path as specified in filebeat.yml
  #     - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
  #     - ./auditbeat/dashboards:/usr/share/auditbeat/kibana/7/dashboard:ro
  #   environment:
  #     - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-elasticsearch:9200}
  #     - KIBANA_HOST=${KIBANA_HOST:-kibana:5601}
  #     - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
  #     - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
  #   depends_on:
  #     - elasticsearch
  #     - kibana
  #   networks:
  #     - elk
  #     - host
  #   deploy:
  #     mode: replicated
  #     replicas: 1

  heartbeat:
    image: store/elastic/heartbeat:7.5.2
    user: root
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-elasticsearch:9200}
      - KIBANA_HOST=${KIBANA_HOST:-kibana:5601}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD-changeme}
      # Uncomment for hosts that use icmp protocol
      - ICMP_HOSTS=["localhost"]
      - TCP_HOSTS=["${ELASTICSEARCH_HOST:-elasticsearch:9200}","${KIBANA_HOST:-kibana:5601}","logstash:9600"]
      - HTTP_HOSTS=["http://${KIBANA_HOST:-kibana:5601}","http://logstash:9600"]
    configs:
      - source: heartbeat_config
        target: /usr/share/heartbeat/heartbeat.yml
    depends_on:
      - elasticsearch
      - kibana  
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
  

configs:
  elastic_config:
    file: ./elasticsearch/config/elasticsearch.yml
  elastic_logs_config:
    file: ./elasticsearch/config/log4j2.properties
  logstash_config:
    file: ./logstash/config/logstash.yml
  logstash_logs_config:
    file: ./logstash/config/log4j2.properties
  kibana_config:
    file: ./kibana/config/kibana.yml
  metricbeat_config:
    file: ./metricbeat/config/metricbeat.yml
  filebeat_config:
    file: ./filebeat/config/filebeat.yml
  # auditbeat_config:
  #   file: ./auditbeat/config/auditbeat.yml
  heartbeat_config:
    file: ./heartbeat/config/heartbeat.yml

volumes:
  elastic_data:
    driver: local
  filebeat_data:
    driver: local


networks:
  elk:
    driver: overlay