version: '3.7'

services:
    #################### AUDITBEAT INSIDE A CONTAINER IS UNDER DEVELOPMENT ####################
  auditbeat:
    image: docker.elastic.co/beats/auditbeat:${ELASTIC_VERSION:-7.5.2}
    # https://github.com/docker/swarmkit/issues/1951
    # Need to override user so we can access the log files, and docker.sock
    user: root 
    volumes:
      - ./config/auditbeat.yml:/usr/share/auditbeat/auditbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      # This is needed for filebeat to load container log path as specified in filebeat.yml
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      - ./auditbeat/dashboards:/usr/share/auditbeat/kibana/7/dashboard:ro
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-elasticsearch:9200}
      - KIBANA_HOST=${KIBANA_HOST:-kibana:5601}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
    networks:
      - elk

networks:
    elk:
        driver: overlay